"""Utility functions and helpers."""

from .exceptions import (
    BaseAIBackendException,
    ErrorCategory,
    AuthenticationError,
    InvalidTokenError,
    MissingAuthHeaderError,
    ValidationError,
    InvalidLocaleError,
    InvalidChallengeTypeError,
    RateLimitError,
    AIServiceError,
    AgentUnavailableError,
    CrewExecutionError,
    FlowExecutionError,
    ModelInferenceError,
    MediaProcessingError,
    UnsupportedMediaFormatError,
    FileSizeLimitError,
    DatabaseError,
    ConnectionError,
    QueryExecutionError,
    WebSocketError,
    WebSocketConnectionError,
    WebSocketTimeoutError,
    ConfigurationError,
    MissingConfigError,
    InvalidConfigError,
    ExternalServiceError,
    SupabaseError,
)

from .error_handler import (
    StructuredLogger,
    logger,
    ErrorMonitor,
    error_monitor,
    handle_exception,
    error_handler_middleware,
    with_error_handling,
    with_retry,
    ErrorContext,
    HealthChecker,
    health_checker,
)

__all__ = [
    # Exceptions
    "BaseAIBackendException",
    "ErrorCategory",
    "AuthenticationError",
    "InvalidTokenError",
    "MissingAuthHeaderError",
    "ValidationError",
    "InvalidLocaleError",
    "InvalidChallengeTypeError",
    "RateLimitError",
    "AIServiceError",
    "AgentUnavailableError",
    "CrewExecutionError",
    "FlowExecutionError",
    "ModelInferenceError",
    "MediaProcessingError",
    "UnsupportedMediaFormatError",
    "FileSizeLimitError",
    "DatabaseError",
    "ConnectionError",
    "QueryExecutionError",
    "WebSocketError",
    "WebSocketConnectionError",
    "WebSocketTimeoutError",
    "ConfigurationError",
    "MissingConfigError",
    "InvalidConfigError",
    "ExternalServiceError",
    "SupabaseError",
    # Error Handling
    "StructuredLogger",
    "logger",
    "ErrorMonitor",
    "error_monitor",
    "handle_exception",
    "error_handler_middleware",
    "with_error_handling",
    "with_retry",
    "ErrorContext",
    "HealthChecker",
    "health_checker",
]
